### ISSUE TITLE
USER STORY: Fastest lap

### ISSUE THREAD

**Issue by Linushf** [Linushf/My-First-Agile-Project#1]
**In order to** compare my speed **as a** runner, **I can** post my fastest lap to the web page.

### Acceptance Criteria
- See my rank compare to others
- Rank to me in numeric order starting from the fastest

### Tasks
- [ ] Add form for user to input their result.
- [ ] Create interactive table for ranking.
- [ ] Create HTML/CSS for presentation.
