### ISSUE TITLE
USER STORY: Best running trail

### ISSUE THREAD

**Issue by Linushf** [Linushf/My-First-Agile-Project#2]
As a **runner** I can **see what trail is the most popular** so that **go there if I haven't been there**

### Acceptance Criteria:
- See how many votes have been made.
- To see length of track.

### Tasks
- [ ] Create multiple choice (radio) question.
- [ ] Create HTML to display result.
- [ ] Add vote counter.
