### ISSUE TITLE
USER STORY: News

### ISSUE THREAD

**Issue by Linushf** [Linushf/My-First-Agile-Project#3]
As an **editor** I can **publish news** so that **website visitors can read about the latest news concerning running**

### Acceptance Criteria
- Easy way to upload articles.
- Displayed in a certain area of the web page.
- Time displaying when an article was published.

### Tasks
- [ ] Create HTML/CSS to hold news feed.
- [ ] Create an easy input method for an editor to publish news.
- [ ] Add visible timestamp to all articles that are published.
